ImsService: ImsApp: Fix fatal crash of OplusImsServiceControllerExt
11-18 04:07:36.451  2627  2627 E AndroidRuntime: FATAL EXCEPTION: main
11-18 04:07:36.451  2627  2627 E AndroidRuntime: Process: com.mediatek.ims, PID: 2627
11-18 04:07:36.451  2627  2627 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mediatek/ims/OplusImsServiceControllerExt;
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at com.mediatek.ims.ImsApp.onCreate(ImsApp.java:92)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1386)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7398)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:107)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at android.os.Looper.loopOnce(Looper.java:232)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:317)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:8592)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
11-18 04:07:36.451  2627  2627 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
11-18 04:07:36.451  2627  2627 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.mediatek.ims.OplusImsServiceControllerExt